#!/usr/bin/env sh

# Load scripting addition
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout
yabai -m config layout bsp

# Gaps
yabai -m config window_gap     8

echo "yabai config loaded"
